<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.1" />
	</ItemGroup>
	<ItemGroup>

	  <ProjectReference Include="..\..\BuildingBlocks\HelperService\MintCart.Caching\MintCart.Caching.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\HelperService\MintCart.Logging\MintCart.Logging.csproj" />
	  <ProjectReference Include="..\..\BuildingBlocks\HelperService\MintCart.Identity\MintCart.Identity.csproj" />
	  <ProjectReference Include="..\..\BuildingBlocks\HelperService\MintCart.Validator\MintCart.Validator.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\HelperService\MintCart.Enum\MintCart.Enum.csproj" />
	  <ProjectReference Include="..\MintCart.Api.Customer.Data\MintCart.Api.Customer.Data.csproj" />
	  <ProjectReference Include="..\MintCart.Api.Customer.Domain\MintCart.Api.Customer.Domain.csproj" />
	</ItemGroup>
</Project>

