<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.0.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Google.Protobuf" Version="3.25.2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.60.0" />
    <PackageReference Include="Grpc.Tools" Version="2.60.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\HelperService\MintCart.Caching\MintCart.Caching.csproj" />
    <ProjectReference Include="..\BuildingBlocks\HelperService\MintCart.Configuration\MintCart.Configuration.csproj" />
    <ProjectReference Include="..\BuildingBlocks\HelperService\MintCart.Enum\MintCart.Enum.csproj" />
    <ProjectReference Include="..\BuildingBlocks\HelperService\MintCart.Extensions\MintCart.Extensions.csproj" />
    <ProjectReference Include="..\BuildingBlocks\HelperService\MintCart.Permission\MintCart.Permission.csproj" />
    <ProjectReference Include="..\BuildingBlocks\HelperService\MintCart.Validator\MintCart.Validator.csproj" />
    
    <ProjectReference Include="..\MintCart.Api.Business\MintCart.Api.Business.csproj" />
    <ProjectReference Include="..\MintCart.Api.Data\MintCart.Api.Data.csproj" />
    <ProjectReference Include="..\MintCart.Api.Domain\MintCart.Api.Domain.csproj" />
    <ProjectReference Include="..\MintCart.Api.Core\MintCart.Api.Core.csproj" />
  </ItemGroup>

</Project>
