/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary": "#006a61",
        "primary-container": "#4cbcaf",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "secondary": "#3f6560",
        "secondary-container": "#bfe8e1",
        "secondary-fixed": "#c2ebe4",
        "secondary-fixed-dim": "#a6cfc8",
        "tertiary": "#95482d",
        "tertiary-container": "#f29271",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59c",
        "surface": "#f8fafa",
        "surface-bright": "#f8fafa",
        "surface-dim": "#d8dada",
        "surface-variant": "#e1e3e3",
        "surface-container": "#eceeee",
        "surface-container-low": "#f2f4f4",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e3",
        "surface-container-lowest": "#ffffff",
        "background": "#f8fafa",
        "on-primary": "#ffffff",
        "on-primary-container": "#004841",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#446964",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#6d2a11",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3d4947",
        "outline": "#6d7a77",
        "outline-variant": "#bcc9c6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3131",
        "inverse-on-surface": "#eff1f1",
        "inverse-primary": "#6bd8cb",
        "mint-green": "#3EB489",
        "charcoal": "#36454F"
      },
      "borderRadius": {
        "none": "0",
        "xs": "2px",
        "sm": "4px",
        "DEFAULT": "4px",
        "md": "6px",
        "lg": "8px",
        "xl": "12px",
        "2xl": "16px",
        "3xl": "24px",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
